---
title: "Cleaning and processing 3-hourly TRMM data"
author: "Faith Musili"
output:
  html_document: default
  pdf_document: default
---

```{r load required packages, eval=FALSE}
library(raster)
```

```{r Read files downloaded files, eval=FALSE}
 trmmImages<-list.files(path = "Data/",pattern = "*.7.tif$|*.7A.tif$",full.names = TRUE,recursive = TRUE)
```

```{r replace all 9999 (missing data) with 0, eval=FALSE}
for (i in 1:length(trmmImages)){
  image<-raster(trmmImages[i])
  image[image == 9999] <- 0
  writePath<-substr(trmmImages[i],1,nchar(trmmImages[i]))
  writeRaster(image,writePath,format="GTiff", overwrite=TRUE)
}
```

```{r create daily  layer  from hourly files, eval=FALSE}

HourlytoDaily<-list.files(path ="Data/",pattern = c(".*3B42.*\\.7.tif$|.*3B42.*\\.7A.tif$"),full.names = TRUE,recursive = TRUE )

hourlyimagefiles<-ifelse(nchar(HourlytoDaily)==39,
                         substr(HourlytoDaily,1,nchar(HourlytoDaily)-22),
                         substr(HourlytoDaily,1,nchar(HourlytoDaily)-23))

Days<-unique(hourlyimagefiles)
  
  for (i in 1:length(Days)){
    
    hourlyImage<-list.files(path=Days[i],pattern = c(".*3B42.*\\.7.tif$|.*3B42.*\\.7A.tif$"),full.names = TRUE)

    dailystack<-stack(lapply(hourlyImage,raster))
    
    dailyimage<-stackApply(dailystack,rep(1,nlayers(dailystack)),fun = sum)
    
    folder<-as.character(Days[i])
    date<-ifelse(nchar(hourlyImage)==41,substr(hourlyImage[1],24,nchar(hourlyImage[1])-10),substr(hourlyImage[1],24,nchar(hourlyImage[1])-9))
    
     outfilename<-paste0(folder,"Daily_",date[1],".tif")
     
     writeRaster(dailyimage,outfilename,format="GTiff", overwrite=TRUE)
    
    }
```

```{r create monthly  layer  from daily layers, eval=FALSE}

DailytoMonthly<-list.files(path ="Data/",pattern = ".*Daily_.*\\.tif$",full.names = TRUE,recursive = TRUE )

dailyimagefiles<-substr(DailytoMonthly,1,nchar(DailytoMonthly)-21)

Months<-unique(dailyimagefiles)

for (i in 1:length(Months)){
  
  dailyimages<-list.files(path = Months[i],pattern = ".*Daily_.*\\.tif$",full.names = TRUE,recursive = TRUE)
  
  Monthlystack<-stack(lapply(dailyimages,raster))
  
  Monthlyimage<-stackApply(Monthlystack,rep(1,nlayers(Monthlystack)),fun=sum)
  
  folder<-as.character(Months[i])
  Month<-substr(dailyimages[1],25,nchar(dailyimages[1])-6)
  
  outname<-paste0(folder,"Monthly_",Month,".tif")
  
  writeRaster(Monthlyimage,outname,format="GTiff", overwrite=TRUE)
}
```

```{r stack all monthly layers  together, eval=FALSE}
trmmfinal<-list.files(path = "Data/",pattern =".*Monthly_.*\\.tif$" ,recursive = TRUE,full.names = TRUE)

trmmfinalBrick<-brick(lapply(trmmfinal,raster))
names(trmmfinalBrick)<-paste0("trmm.",1:nlayers(trmmfinalBrick))

writeRaster(trmmfinalBrick,"Data/trmmfinal.tif",format="GTiff", overwrite=TRUE)
```